name: semift
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.4.1
  - torchvision=0.19.1
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  - pillow
  - h5py
  - pyyaml
  - matplotlib
  - opencv
  - tensorboard
  - pip:
      - easydict
      - einops
      - tensorboardX
      - accelerate
      - transformers
      - huggingface_hub
      - pytest
      - pandas
      - openpyxl
      - seaborn
