# arguments for dataset
dataset: potsdam
nclass: 5
# crop_size: 512
crop_size: 518
data_root: '/data1/users/lvliang/project_123/dataset/'
epochs: 75
batch_size: 4 # per GPU x 4 GPUs
lr: 0.00005
# lr: 0.0001
lr_multi: 1.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 5
conf_thresh: 0.95
amp: True
workers: 1
ignore_index: 5
PATCH_SIZE: 32
MAX_RATIO: 0.75
thresh_init: 0.85
# eval_mode: original

# eval_mode: resize
eval_mode: original
model: dpt
backbone: dinov2_base
lock_backbone: False
pretrain: True
multi_grid: False
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]
warm_up: 10
img_scales: [0.25, 0.5, 1.5, 2.0]
feat_s_scales: [0.75]
feat_l_scales: [1.25]