# arguments for dataset
dataset: vaihingen
nclass: 5
# crop_size: 518
crop_size: 512
data_root: '/data1/users/lvliang/project_123/dataset/'
epochs: 75
batch_size: 4 # per GPU x 4 GPUs
lr: 0.00005
# lr: 0.000005
# lr: 0.0001
lr_multi: 40.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 5
conf_thresh: 0.95
amp: True
workers: 1
ignore_index: 5
PATCH_SIZE: 32
MAX_RATIO: 0.75
eval_mode: original

# eval_mode: resize
# eval_mode: slide_window
model: dpt
# backbone: dinov2_small
backbone: dinov3_base
lock_backbone: False